# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by tank clone
# This file reflects the paths in the pipeline configuration
# entity which is associated with this location (Developing).

Windows: 'C:\Code\shotgun\tk-conf-single'
Darwin: '/Code/shotgun/tk-conf-single'
Linux: '/Code/shotgun/tk-conf-single'

# End of file.
